### ISSUE TITLE
"Final Harvest" Variant

### ISSUE THREAD

**Issue by blawrence719** [ebeshero/EmilyDickinson16#11]
Ignore the title of this, I hit a button on my keyboard and published this issue in the middle of typing the title and hadn't even typed up the issue yet.

But anyway, I've just pushed a file that's a sample of Poem 3 with the `@wit` for the "Final Harvest" version of the poem. I was unsure how to set the id at the top, so for now they are labeled as `#fh` but it isn't defined as anything yet.

I'm not sure if this is what we were talking about in class, I just figured I'd try it on one with only a couple of changes. Correct me if I'm wrong, but when I looked, it seemed like "Final Harvest" had most of the poems. Also, I wasn't sure how to add more than one `@wit` so I just kept creating new `<rdg>` elements.

**Comment by brookestewart** [comment]
I'm not sure of the answers to your questions, but it looks good to me! Anyone else? 

I have class until 7, but I was planning on making a complete list of which poems were published where. I also need to push the poems with the corrected transcriptions, so I will do that as well. 

What exactly did we agree to have completed for tomorrow? Sorry, I was quite tired in class and forgot!

**Comment by ebeshero** [comment]
Hi Brookes both! I will take a look at the files, and let's work on a task list here. I'm en route dropping off books  from our book drive today.

**Comment by brookestewart** [comment]
Here is the breakdown of where each poem was published, taken from the original website. The Final Harvest and Centenary Editions have the most complete list, each only missing one poem.
Poem 2 was published the most, at 4 times. 

1890 Poems, edited by Mabel Loomis Todd and Thomas Wentworth Higginson `#poems1`
4, 10
1891 Poems, Second Series, edited by Mabel Loomis Todd and Thomas Wentworth Higginson `#poems2`
1
1896 Poems, Third Series, edited by Mabel Loomis Todd `#poems3`
3, 5, 9
Further Poems `#fp`
2, 7
Centenary Edition `#ce`
1, 2, 3, 4, 5, 7, 9, 10, 11
Final Harvest `#fh`
1, 2, 3, 4, 5, 6, 7, 9, 10
Bolts of Melody `#bm`
8
Atlantic Monthly `#am`
2

**Comment by ebeshero** [comment]
@blawrence719 Brooke: This code looks good: Yes, this is how you work in new variants, but we should add information in the file to identify th witnesses and explain what we're doing. We can talk about how to do that tomorrow.

**Comment by ebeshero** [comment]
@brookestewart Great work with plotting this--and it is probably information we will want to represent on the new website! This is very helpful. Let's think about which of these versions are most interesting to code and study.

**Comment by ebeshero** [comment]
@amielnicki @nlottig94 Have a look at what the Brookes did here with a) coding in a new witness on poem 3 and b) noting which poems were published where. Do we want to represent each of these in our code to study how these poems were altered, or select some that look especially interesting? 

Brooke Lawrence's code of poem 3 with the Final Harvest edition alterations marked is here: https://github.com/ebeshero/EmilyDickinson16/commit/04c4f241f8d175650f7f3ba12c92ace652ec81cb

**Comment by nlottig94** [comment]
@brookestewart I was on the original Emily Dickinson site and could not find where you got the Atlantic Monthly.... Enlighten me???

**Comment by brookestewart** [comment]
@nlottig94 http://www.cs.virginia.edu/cgi-bin/cgiwrap?user=ajf2j&script=BrowseSpace&BS_file=fascicle16.bsp&BS_node=1601var&BS_edge=Next

You have to click on index, then Fascicle 16, then "this poem with its variants" and "next Fascicle poem with its variants" and it will be on the bottom. I went through all of the poems that way.

**Comment by blawrence719** [comment]
@brookestewart Unless you have already started adding variants to the poems, I am going to work with poems 1-5

**Comment by brookestewart** [comment]
@blawrence719 Sorry, I'm just now getting a chance to get on here! That works for me! 
As far as the em dash goes, `&#8212;` works for `—` instead of a regular dash. If you do the ctrl and f and search for alt0151, that should find all the em dashes in the code and you can just replace them with the `&#8212;`. 
Is this what we were talking about on Wednesday, guys? If so, I could go ahead and do that as well.
@amielnicki @nlottig94 @ebeshero

**Comment by blawrence719** [comment]
Just finished pushing files with poems 1-5 and all of their variants. But looking at @brookestewart 's post, I'm realizing I forgot to change the em dashes. I will fix this later.
