### ISSUE TITLE
Coding rdg wit when the witnesses agree on something

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/EmilyDickinson16#12]
I can't remember how we decided to resolve this. When two (or more) witnesses agree to represent something (like "firmest" in the following line):

```
<l>Put me in on the <app>
                  <rdg wit="#fh">firmest </rdg>
                  <rdg wit="var0">firmest </rdg>
                  <rdg wit="var1">tightest </rdg>
                  <rdg wit="var2">highest—</rdg>
               </app>side—</l>
```

Do we want to go with representing each `@wit` in a separate `<rdg>` element, or do we want to collapse those into one with two attribute values separated by a white space?  (That would look like this:)

```
<l>Put me in on the <app>
                  <rdg wit="var0 #fh">firmest </rdg>
                  <rdg wit="var1">tightest </rdg>
                  <rdg wit="var2">highest—</rdg>
               </app>side—</l>
```

If you do that, you need to `tokenize()` on white space in your Schematron to make sure your attribute values are correctly listed. (And I'm happy to share my Schematron code for that from the Digital Mitford project so you have a model.) There are advantages and complications associated with each approach, but one thing to consider here is that you may want to track where printed publications made use of particular variants written by Emily Dickinson herself. We should make clear to everyone here what approach makes the most sense for the group so we're all on the same page! 

@blawrence719 @brookestewart @nlottig94 @amielnicki

**Comment by brookestewart** [comment]
I don't remember either... @blawrence719?
@nlottig94 you did the Schematron, correct? Does it matter to you?

**Comment by nlottig94** [comment]
I thought that we had discussed doing the second option 
(`<l>Put me in on the <app>
                  <rdg wit="var0 #fh">firmest </rdg>
                  <rdg wit="var1">tightest </rdg>
                  <rdg wit="var2">highest—</rdg>
               </app>side—</l>-`)

However, I believe @amielnicki was doing the Schema...
