### ISSUE TITLE
listWit examples

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/EmilyDickinson16#13]
From the TEI P5 page: Here are some examples of listWit: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/examples-listWit.html

For links outward, use `<ref target="http://...stuff">Title of Site</ref>`

**Comment by nlottig94** [comment]
The listWit section for each poem is finished!  If someone could double check that I have all of the witnesses in each poem, that would be great!!  They are all using the XML poems in the Dickinson poems!  I didn't rename anything!!
