### ISSUE TITLE
Poem 11 and the Alternate Version in the Letter to Susan

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/EmilyDickinson16#16]
@brookestewart @amielnicki @nlottig94 @blawrence719 Here is a manuscript photo facsimile of Poem 11's different version outside Fasicle 16, as written in a letter to Susan Dickinson, her sister-in-law and very close friend. 

http://www.edickinson.org/editions/1/image_sets/237453

From looking at the Creative Commons Permissions on this site, I think we are clear to use this image on our own site, and image mapping won't be a problem.

Brooke Stewart, I think, is taking the versioning of this on, using the witness definitions we came up with here: https://github.com/ebeshero/EmilyDickinson16/issues/15

For more on Susan, and on who Mabel Loomis Todd was, here's a good starting point: https://www.emilydickinsonmuseum.org/susan_dickinson
And lots more here: http://archive.emilydickinson.org/susanemilylivesinletters.html

I wonder if the rest of the letter to Sue (with this poem in it) is posted anywhere? (I have not gone searching for it.)

**Comment by brookestewart** [comment]
@ebeshero I cannot find the second page of this poem, at least not on the archive site... The last three lines are missing.

**Comment by ebeshero** [comment]
@brookestewart Interesting! I can't find it in the Harvard edickinson.org site either, but I also don't see any evidence from the Harvard site's TEI edition that anything was missing in their transcription. I bet the editors there _did_ see that page, and I wonder if the problem is just a missing image on their website. There are two ways to find out:
1) Go to look at the Dickinson manuscript papers (literally the very papers she wrote on) at Amherst College or in the Harvard collections (after figuring out which one has the letter to Susan containing this poem) after some screening by the librarians to make sure you're safely trained to handle manuscripts without damaging them. (I think we can't easily manage this before the project is due.)

2) Order the three-volume hardbound Variorum edition of Emily Dickinson's Poems through the library--and as it so happens we have a copy at Hillman Library in Oakland, I have just requested it through the university libraries' "Get It" service to be sent to Greensburg ASAP. It could be here by Friday or maybe early in Finals Week--I'll write when it arrives.

For now, I think you should add a comment tag in our project TEI to note the missing image at edickinson.org, and be precise about what is missing and which lines you have not seen in the photo facsimile of the manuscript. You can access their project's transcription and even their TEI code of the poem as written to Sue, so I think you can safely use that as your reading witness.

When we get the Franklin Variorum text from the library we can check to see if page two is there. If it _is_ there after all. someone on our team really should write to the edickinson.org editors (find the appropriate contact) and inform them that they are missing this image.

**Comment by brookestewart** [comment]
Okay, I will finish the poem using their transcription and make a comment tag!
As for contacting them, the only contact I could find was a support form, so I filled it out to let them know about the missing image.

**Comment by brookestewart** [comment]
They sent me the missing image of the manuscript!! I'm on mobile, so I can't post it now, but I definitely will when I get home from work tonight, as well as fix that piece that was lost from the merge conflict!

**Comment by ebeshero** [comment]
Wow @brookestewart ! That is wonderful! Did you write to someone at the edickimsonedickinson.org site? Tell us more! Yay!

**Comment by nlottig94** [comment]
I actually put it in the correct folder in our GitHub!!  @brookestewart forwarded the email to me!!

**Comment by ebeshero** [comment]
Ahhh! Don't keep your poor professor in suspense...I'd love to see the message! I am so glad and surprised that they responded--and so quickly too!
