### ISSUE TITLE
Work This Weekend!

### ISSUE THREAD

**Issue by alexthattalks** [ebeshero/EmilyDickinson16#18]
I have worked all day and done a TON to move us forward with my XSLT file to evaluate the poems that have been completely marked up.

As of now, I have ran my XSLT on Poems 1 - 5, and if I do say so myself, everything looks really good!

Currently, I have it set so the page loads with the Fascicle versions of the poem. The colored buttons on the side toggle each of the versions associated with that poem on or off. 

It took a good long while, but I have a conditional XSLT and JavaScript file written, so only the buttons of the poems that appear in the List of Wit at the beginning of each poem display in the sidebar.

Let me know what you think!!!

http://dickinson16.newtfire.org/mielnicki/1601.html
http://dickinson16.newtfire.org/mielnicki/1602.html
http://dickinson16.newtfire.org/mielnicki/1603.html
http://dickinson16.newtfire.org/mielnicki/1604.html
http://dickinson16.newtfire.org/mielnicki/1605.html

:+1:

**Comment by alexthattalks** [comment]
@ebeshero Any input?

**Comment by ebeshero** [comment]
@amielnicki @nlottig94 @brookestewart @blawrence719 Great work, Alex! The page design is gorgeous! (Sorry I haven't had time to reply until now, what with the GitHub crisis yesterday and a back-to-back meetings and classes all day.) But I'm looking now, and here are some issues I notice: 
- Take a look at this poem: http://dickinson16.newtfire.org/mielnicki/1601.html and click on each of the published variants. I _think_ I understand what you're doing here: On click, you make a particular published text's view visible, but:

a) When the published text matches the manuscript, we see the words doubled. (Is that necessary?)

b) When I go to click on a different published version, the previous version I clicked on remains visible, and it makes for something a little cluttered and confusing to follow: Are we seeing _too much_ at once? 
I wonder if there are some other ways to handle the JavaScript, such as with pop-up boxes?

c) Think about whether you want to handle the variants in the manuscript differently from the variants in the print publications: We read those variants differently in Real Life, don't we? Dickinson's variants seem intended to be read together as different options. The print publications represent different editors' decisions in representing these texts, in which for the most part they _excluded_ some of Dickinson's variants.  

Now that you've got some great working JavaScript, what I'm suggesting is to think about some different ways to apply it!  :+1:

**Comment by ebeshero** [comment]
One possibility might be to create two separate viewboxes: one for the Fascicle 16 version and its variants, and the other, to sit next to it, to contain different published versions, with their variations from fascicle 16 highlighted (and the toggle boxes to cycle through each). Thoughts?

**Comment by ebeshero** [comment]
@amielnicki @nlottig94 @brookestewart @blawrence719 
Wait: I think I understand what you're doing: On click, you want the different variants to sit side by side to help the reader to compare them. That's okay so long as you provide some instructions and explanations to the viewer... But let's think about if there are some other things we can do with JavaScript to help set these in relation to each other, and consider if you want a different viewbox for Fascicle 16 vs. the Published versions (or not!)

**Comment by alexthattalks** [comment]
Yep! That's exactly what I was going for with that design. To be able to compare the variants side by side.

The JavaScript will also be triggering highlighting of the boxes over the images we map of each variant.

I also realize documentation needs added so the user knows what to do, as well as the documentation we talked about for judgement calls, why we did things, etc.
