### ISSUE TITLE
Bios Bios Everywhere!

### ISSUE THREAD

**Issue by alexthattalks** [ebeshero/EmilyDickinson16#19]
Hey all!

If you can send a brief Bio about yourself for our website, that would be WONDERFUL!!

Just go ahead and post the Bio into this issue and I will add it to our about page with the picture we took in class today.

@nlottig94 @blawrence719 @brookestewart 

Thanks guys!

**Comment by nlottig94** [comment]
Are we all turning in selfies as well?!?

**Comment by alexthattalks** [comment]
Sure! We'll have individual selfies plus the group:)

**Comment by brookestewart** [comment]
![12003276_1108041695890138_1143117249444451493_n](https://cloud.githubusercontent.com/assets/14084707/11689382/b41eadd6-9e5f-11e5-9f19-e85a80fddfe8.jpg)
Here is my SELFIE. Happy, @nlottig94?!
Brooke Stewart is a 20 year old Sophomore at University of Pittsburgh at Greensburg, majoring in English Literature. She works part-time at Dairy Queen on the weekends. She enjoys reading, traveling, and exploring outdoors. She plans to continue her studies and graduate from UPG in 2018.

**Comment by blawrence719** [comment]
Brooke Lawrence is a 20 year old Junior at University of Pittsburgh at Greensburg, majoring in Creative and Professional Writing with a minor in Gender Studies and pursing a Digital Studies Certificate. She enjoys climbing mountains and writing about her adventures. She plans to graduate in 2017 and continue her studies in grad school.

**Comment by blawrence719** [comment]
![12358215_10201058979991998_2057620615_n](https://cloud.githubusercontent.com/assets/14064682/11736697/542c9564-9f9f-11e5-9cca-2305bf697a32.jpg)

Here is my selfie of defeat. Is everyone happy now? Also, sorry for the bad quality. My phone has a really crappy front facing camera.
