### ISSUE TITLE
Merge Conflict

### ISSUE THREAD

**Issue by brookestewart** [ebeshero/EmilyDickinson16#23]
I went to sync Github before I started working and it said there was a merge conflict. I'm not sure what to do, but I know I don't want to mess anything up! This is what it looks like:
![merge](https://cloud.githubusercontent.com/assets/14084707/11733218/43452ade-9f79-11e5-89b1-07ee483fa564.png)

**Comment by alexthattalks** [comment]
Uncheck the box next to the file that has the conflict, then you should be able to commit the other changes. 

Then, with the file you changed, we can fix it tomorrow in class. Just don't commit that one file.
