### ISSUE TITLE
Dickinson Site Enhancements

### ISSUE THREAD

**Issue by alexthattalks** [ebeshero/EmilyDickinson16#26]
Hello All!

I would like to invite you to look at the site so far. I have added a few things after working for 8 hours yesterday. I am excited for you to take a look!! **Don't be alarmed** - Poem 11 is not complete yet. I still have a couple things to do to that one before I publish it. It will be done by end of day today.

The new link is:

http://dickinson16.newtfire.org/1601.html

The changes are:
- 'View Original Variant Images' Button - When you click the button, it brings up a modal box using CSS and JavaScript that displays the name and thumbnail of the original images for that particular poem. When you click on each image, it loads the larger version in a new tab in your browser. This box is dynamically generated based on the existence of files in our 'listRef' element in each XML file.
- 'View Original XML' Button - When you click the button, it takes you to the original XML file for that poem, in a new tab so you don't lose your place where you were. This is dynamically generated based on the XML file reference in our 'listRef' element in each XML file.
- JavaScript for loading Poem Variant Images - I have written in the JavaScript to bring up the correct image with the corresponding variant when you click the button. Currently, it is set to do the same as with the text variants, in that it will display multiple images on top of one another, if you have multiple variants "turned on" at once. I think it makes sense being that we give the option for multiple variants to be displayed at once.
- XSLT Parse errors corrected - Because of how my XSLT steps through each of the poems, It was necessary for me to add certain white spaces between tags for the parser to read it correctly. These white spaces do not actually display in the text, but are crucial to the text displaying in the correct order in certain complex line situations.
- Style changes - I have added gray dashed lines beneath each poem line to help with readability. I have also made the line numbers black boxes with white numbers to set them apart from the line. With this, I adjusted the line height to make it a bit easier to read. I have also changed the poem text and title texts to reflect the Open Sans font... a Sans Serif font that is very clean and easy on the eyes.
- Cropped and joined images - For the images that display on the page next to the variant text, I have joined together the multipage ones to allow for a more streamlined viewing/reading experience. I think it looks really slick. When I cropped and joined them, I redid all of the image mapping, and Nicole is currently adding the @alt and @href info to each file.
- Validation - with the exception of a few tiny errors here and there, the poems all pass HTML5 validation... validiting without me even trying! I will take care of ensuring all files validate before the project is turned in.
- Moved web files to root of website - I moved the files out of the 'mielnicki' folder, and into the main area of the web server.
- Published Web Files to GitHub - I pushed all of my web files, including the JavaScript and CSS to GutHub. Changes can be made there (after Nicole is done with her task) before they are pushed to the web server. I will take care of making sure the files mirror each other.

I will be posting a separate issue with things that we still need to do to get our project to completion!

Thanks everyone!

@ebeshero @brookestewart @blawrence719 @nlottig94

**Comment by nlottig94** [comment]
@amielnicki it looks awesome!!!!  It'll be really cool once we get the `@alt` / `@title` to come up!!!

**Comment by alexthattalks** [comment]
I just ascertained the email alias `dickinson@pitt.edu` which I can set to automatically forward to all of us when a message is received :)
