### ISSUE TITLE
Left To-Do

### ISSUE THREAD

**Issue by alexthattalks** [ebeshero/EmilyDickinson16#27]
Here is our to-do list to wrap up the project. I know it looks like alot is still assigned to me, but it's just the number of items, there is not very much to do with each thing.
- ~~SVG - **Brooke Stewart | @brookestewart** - The SVG for the dash comparison needs done so we can publish to the site.~~
- ~~Info About SVG - **Brooke Stewart | @brookestewart** - Findings derived from the SVG and what the graph means, etc.~~
- ~~Homepage Copy - **Brooke Lawrence | @blawrence719** - Write up about the site, intro, etc.~~
- ~~About Us - **Brooke Lawrence | @blawrence719** - Write up about the group and our class. Alex will add Selfie we took as a group.~~
- ~~Image Mapping `@alt` and `@href` - **Nicole Lottig | @nlottig94** - Put in data for the `@alt` and `@href` attributes for each image map.~~
- ~~Contact Us Page - **Alex Mielnicki | @amielnicki** - Write the code for the contact us page for us to be contacted about the project. Got the dickinson@pitt.edu address.~~
- ~~Members Page - **Alex Mielnicki | @amielnicki** - Some styling on the bios and images, and some fixes to code. Also, add the Newt from NewtFire to the list.~~
- ~~Instructions - **Alex Mielnicki | @amielnicki** - Write up for users to learn how to read and use the site when viewing images and the variants.~~
- ~~Methodology Page - (Empty page on site): Something to feature the code @nlottig94 @amielnicki .~~
- ~~Conclusions - **Alex Mielnicki | @amielnicki** - Add Brooke's code to site.~~
- ~~Poem 11 - **Alex Mielnicki | @amielnicki** - Finish Poem 11 for the site.~~

**Comment by blawrence719** [comment]
@amielnicki I've pushed a .txt file of the about page that I originally wrote in Word. If you want me to put this into a html file, I can do that tomorrow. I'm also not sure if this is what you were looking for on the about page. If not, let me know and I can make changes. I'll probably have to make changes anyway when I reread it tomorrow seeing as I wrote it at midnight.

Sorry for not working on this sooner, I just finished my finals today!

**Comment by RJP43** [comment]
@blawrence719 just a random word of wisdom, learned the hard way, you want to be careful with writing in word because there are a lot of typical characters like the quotations marks, apostrophes, and sometimes brackets/parenthesis (just to name some off the top of my head) of most fonts that appear as jumbled messes when copied into oXygen and rendered in HTML. If doing it for spell check write in oXygen then copy into word see the error and manually fix them in the oXygen text or if you already have a bunch of text typed using word make sure you do find and replace on these characters ... hope this was helpful

**Comment by ebeshero** [comment]
@blawrence719 As you know, I agree pretty strongly with @RJP43  on this. Maybe you can be proofreading what you drafted in Word by reworking the text with code in oXygen.

**Comment by nlottig94** [comment]
@amielnicki  @blawrence719  @brookestewart  @ebeshero 
Here are a list of links to our GitHub Stuff so wherever we need to paste them on our page, they'll be easy to find.  All I need to add to this is Alex's XSLT file (which is on the way) to this list:

Old Files from Br. B.'s Site and Experiements from Our Homeworks:
https://github.com/ebeshero/EmilyDickinson16/tree/master/Old%20Files

Original Coded Poems:
https://github.com/ebeshero/EmilyDickinson16/tree/master/Old%20Files/TEI-XML

New Coded Poems:
https://github.com/ebeshero/EmilyDickinson16/tree/master/Dickinson

Image Mapping:
https://github.com/ebeshero/EmilyDickinson16/issues/14

Image Mapping Example in HTML File (Scroll to the bottom of the HTML):
https://github.com/ebeshero/EmilyDickinson16/blob/master/Web%20Files/1601.html

XSLT for SVG Graph (With notes from Dr. B. for alternate ways):
https://github.com/ebeshero/EmilyDickinson16/blob/master/SVG_Files/xslt_to_SVG.xsl

SVG Graph Itself:
https://github.com/ebeshero/EmilyDickinson16/blob/master/SVG_Files/Dickinson_SVG.svg?short_path=db41efc

All Files Used for Webpage:
https://github.com/ebeshero/EmilyDickinson16/tree/master/Web%20Files

Alex's Brilliant CSS file:
https://github.com/ebeshero/EmilyDickinson16/blob/master/Web%20Files/css/styles.css

Alex's Awesome Javascript:
https://github.com/ebeshero/EmilyDickinson16/blob/master/Web%20Files/scripts/dickinson.js

All Images Used In the Webpage:
https://github.com/ebeshero/EmilyDickinson16/tree/master/Web%20Files/img

Alex's XSLT:
http://dickinson16.newtfire.org/xml/dickinson.xsl
