### ISSUE TITLE
Meeting

### ISSUE THREAD

**Issue by brookestewart** [ebeshero/EmilyDickinson16#29]
@blawrence719 we're in Village Hall if you wanted to meet up! We couldn't meet in the classroom.

**Comment by blawrence719** [comment]
I can be up there in about 10 minutes if you're still there

**Comment by brookestewart** [comment]
Me and Nicole actually had to leave. Dr. B might still be there

On Dec 16, 2015, at 6:28 PM, blawrence719 <notifications@github.com<mailto:notifications@github.com>> wrote:

I can be up there in about 10 minutes if you're still there

##

**Comment by blawrence719** [comment]
Yeah I already ran up here and figured that out :/
