### ISSUE TITLE
Brainstorm!

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/EmilyDickinson16#3]
By Friday 10/9: Post your ideas for what we could do with the project's TEI files. researching other texts, and/or website overhauling! @amielnicki @brookestewart @blawrence719 @nlottig94

**Comment by brookestewart** [comment]
I definitely think we all agree that we need a homepage that fully explains the project. In addition, I think it's important to find and fix the transcription errors, as accuracy is pretty important in general. I still think it would be interesting to explore why these particular poems were bound together. This would be something that we could research to help provide context and background. 
As for the layout, one of the main fixes, in my opinion, is the arrangement of the pictures of the manuscripts at the bottom of the pages. It would be a lot easier to understand if they were tidied up and had captions added.

**Comment by nlottig94** [comment]
I agree with @brookestewart that we need to make a homepage that explains what the site is all about and that we should find the transcription errors and correct them.  I also think we could even try to understand and explain why the publishers changed the poems and how this could have altered the meaning of the poems altogether.  I also like how @brookestewart said about finding how and why these specific poems were originally bound together.  I think we could have a more organized page overall if we all worked on it to the best of our abilities!

**Comment by blawrence719** [comment]
I agree with the homepage idea and researching why the poems were bound together. I also think that it would be interesting to find different versions of each of these poems - like the one we discussed after class which had different pronouns in different versions. We also need to figure out the best way that we can show how Dickinson wrote a line two different ways. I am not sure what the best way to do this is, though we can probably brainstorm together and find a way that does not favor one version over the other.

**Comment by alexthattalks** [comment]
A homepage is definitely something we need to tackle. I think we should overhaul the entire look and feel of the site as well. Create something a bit more intuitive and user friendly, with a modern look and feel. "Flat design" is very big right now and I have substantial experience in design concepts, color theory and user experience. This type of design is all about getting the most information across in an easy-to-understand method, with minimalistic tendancies. Most websites you use nowadays (including github) have moved to this type of design. A new look, in addition to fixing transcription errors, improved page organization/navigation, and possibly even added content would give us a great site.
