### ISSUE TITLE
Posting Content to Website

### ISSUE THREAD

**Issue by alexthattalks** [ebeshero/EmilyDickinson16#30]
Hello everyone! 

Since you will most likely need to add things to the site pages after I leave for my trip, I am typing up this little tutorial on how to do so, to make sure everything comes up correctly.

Step 1 - Editing HTML in GitHub

First, sync your GitHub repository to your local computer. Once it is synced, go to the "Web Files" folder and find the HTML file you want to edit. Open it in oXygen. Once the file is open, find the the `<div class="copy">` area. Paste whatever content you would like to add in this area. Be sure any content you add is already inside `<p>` tags.

You will see if you edit the index.html, conclusion.html, or about.html, that there is already text in there. You can reach in and add text to any of those paragraphs and add new paragraphs above, below, in between the ones that are already there. You will also see on those pages how to create a Drop Cap for the first letter of the paragraphs. It is a simple `<span class="drop">T</span>` Where the "T" in the middle is the first letter of the first word of the first paragraph. Make sure you include the `<span>` element inside the `<p>` element for the paragraph.

**Important** - When putting the page's title above the `<p>` elements, be sure to use the `<h2>` element. The site title at the top is the `<h1>` element, so to preserve the hierarchy, make your page title `<h2>`

Once you have completed all of the changes you would like to make to the content, save your file, like usual, and sync your GitHub, committing any changes. 

Step 2 - Moving files to the website

Now that you have edited your files, you need to push them live to the website, so that the website files mirror what is on GitHub. 

To do that, make sure your GitHub is synced so you have the latest version of the file. 

Now, open your FTP client (FileZilla, WinSCP, etc.) and login to the Pittsburgh Supercomuting Center. Once you are logged in, navigate to the project team folder by going up two levels in files from your personal folder, go into the "var" folder, then "www" then "html" then "dickinson16".

**Important** - When putting the files onto the web server, make sure any file you upload has the permissions of 775.

Here, you will find the web files for the project. Now that you are here, on the left side of your FTP client, you should have your file browser to find local files on your computer. Go to and find the folder where you have your local GitHub repository and find the HTML file you edited, inside the "Web Files" folder. Once you have found that file, drag it over to the web server side of the window, and indicate you would like to overwrite what is already there. 

Once you click yes and the file copies over, go to your web browser and check to see if the changes you made are live.

Step 3 - Relax a bit because you're done!

I will be available on my cell phone intermittently until around 4pm Friday (I will be flying most of the day but can answer when I land at my layover and destination). After 4pm Friday, I will have **ZERO - 0 - access to internet** and will only be able to make phone calls or send/receive text messages for emergencies, as I will be leaving the country, and using my cell is very expensive. 

After 4pm Friday, PLEASE refrain from contacting me unless someone has lost a limb or is dying as a result of the project. LOL

It would be helpful if you guys @blawrence719 @brookestewart can test out doing stuff so I can answer any questions you might have today before I leave.

**Comment by ebeshero** [comment]
@amielnicki  Thanks for this very clear tutorial! @blawrence719 will remember I wrote a Facebook message to Michele Ierardi last night to ask for a date when she produced her work and to send her a link to yours. She wrote back this morning! You'll maybe want to incorporate some of this into the site:

"Hi Elisa! Thanks so much for updating me on your work. How exciting! I had a lot of fun exploring the site. As for dates, my then-fiance-now-husband Adam Ferrari and I worked on the original site and BrowseSpace software during the summer of 1997, just after I finished my PhD coursework and first round of exams at UVA. I presented the project in a paper titled, "Translating Emily: Digitally Representing Dickinson's Poetic Production Using Fascicle 16 as a Test Case," at The 1997 Society for Literature and Science Annual Conference, Pittsburgh, PA in November 1997. Here's a link to the schedule. Matt Kirschenbaum was the chair of that panel and a friend of mine at UVA. I can't believe that it is almost 20 years ago! Hope that info is helpful and thanks again for giving my digital humanities work from long ago continued life! All the best, Michele"

Here is a link to the conference where she presented her project in 1997 (back in the age of Web 1.0)! 
http://www.litsci.org/conferences/sls97schedule.pdf

And, there's more--we are talking now about why she didn't continue her project: She wanted to do a much longer PhD dissertation on this at UVa, but...why she didn't is a sobering story about power politics and turf around the millennium. She was told not to work on digitally studying Dickinson because that was "already taken"--and ultimately the whole experience led her away from the project, but she's glad to be reminded of it and rediscover her old work--and she loves exploring what you've done with it!

The turf issue I think involved UVa (University of Virginia) losing to Harvard over building a big digital archive of Dickinson--and what seems ridiculous and sad to me about it now is the idea that a brilliant digital research study like Michele's could be nipped in the bud by people thinking there can be one and only one digital repository, and confusing the scale and authority of something like the big Harvard archive with the kind of intensive work that scholars and students (like you) can do, with Creative Commons licensing and share alike citation practices.

**Comment by blawrence719** [comment]
@amielnicki @ebeshero I have updated the about page with info on Michele Ierardi and I went to put them onto the webspace and I can't override the original about file. I get an error telling me that I don't have permission

**Comment by ebeshero** [comment]
@blawrence719 I'll see if I can edit the permissions, though I bet Alex will too. Meanwhile, here is one more piece of info from Michele Ierardi that we should feature: She is now working on a novel built on a Dickinson poem, "The Bustle in a House" and you may want to link to her blog post on it: http://deaddarlings.com/life-death/
(I might not have the Dickinson line right here, so do get it from her blog!)

**Comment by ebeshero** [comment]
@amielnicki I see that I don't have authority to change permissions on the files in dickinson16! If you can shell in and fix that so the group can post, that would be great!

**Comment by alexthattalks** [comment]
I'll fix them. I'm going into a final now. Give me an hour

**Comment by ebeshero** [comment]
Thanks, @amielnicki !

**Comment by alexthattalks** [comment]
Are you on campus @ebeshero?

**Comment by ebeshero** [comment]
No--at my house! What's up? @amielnicki

**Comment by ebeshero** [comment]
@amielnicki I can come to campus if you need to see me--let me know--but give me about 30 mins!

**Comment by alexthattalks** [comment]
Nope, don't need you to. Just wanted to come to your office if you were here to have you test the new permissions. Can you do that now for me?

**Comment by ebeshero** [comment]
Sure!

**Comment by ebeshero** [comment]
Shelling in now...

**Comment by alexthattalks** [comment]
It may be the case, that people should just open the files and copy and paste in the new content from the GitHub file, rather than overwriting. If they overwrite, they will probably have to modify the permissions every time, versus just editing the file. I don't know if they know how to do that though. That is how I edit websites all the time, but I am using a power-user client for Mac.

**Comment by ebeshero** [comment]
Looks like the permissions have changed....Let me see if I can post a file...

**Comment by ebeshero** [comment]
Just uploaded about.txt (no problems there)... How about I try to post Brooke Lawrence's revised About page?

**Comment by ebeshero** [comment]
Yup--looks like that went through...

**Comment by ebeshero** [comment]
Looks like things are fine now. Did you change permissions on all the directories? Looks like the XML directory is still just you...

**Comment by alexthattalks** [comment]
I was waiting to see if it worked. I have changed XML, Scripts and IMG folders

**Comment by ebeshero** [comment]
Hmmm... img and scripts look the same. XML, too. I don't think I'm allowed in those!

**Comment by ebeshero** [comment]
Anyway, I _can_ update an HTML file in the main directory.

**Comment by alexthattalks** [comment]
Try exiting and going back in. I made everything 775

**Comment by ebeshero** [comment]
Ahh. Yes, it's accessible now! I just had to exit and reenter, right.

**Comment by alexthattalks** [comment]
There are some old folders, namely 'fs16_imgs', 'TEI-XML', 'Other images' that I cannot change. @nlottig94 is going to delete 'fs16_imgs', and @brookestewart  would need to delete 'TEI-XML' and 'Other images' as she created them.

**Comment by ebeshero** [comment]
Or they could just adjust the permissions--but I guess these aren't actually in use on the site, or are duplicated elsewhere, right?

**Comment by alexthattalks** [comment]
Correct, they aren't used, they are located elsewhere and organized differently.

**Comment by alexthattalks** [comment]
I updated my inital comment in this issue with a note about making any file that anyone uploads have 775 permissions.

**Comment by ebeshero** [comment]
Thank you-- I added one line to your https://github.com/ebeshero/EmilyDickinson16/issues/27 about the Methodology page-- I think @nlottig94 or you could probably write it, but let's just be sure who's doing what, since you're heading out!

**Comment by alexthattalks** [comment]
I don't care if I have to write it, it doesn't matter to me. I would be available after 10:30pm tonight to do so, before I leave at 5:50am. I have prior plans starting at 4:30pm (in 12 min) until 10:30pm tonight. If I end up writing it, I think you said on another issue what all you think it should have in it.

**Comment by ebeshero** [comment]
@nlottig94 wrote up a list of GitHub links, on the same issue with what's left to do: https://github.com/ebeshero/EmilyDickinson16/issues/27 Nicole, are you able to write that into a proper page to describe and feature the coding methods the team deployed?

**Comment by alexthattalks** [comment]
I am heading to my plans this evening. I will be looking at my phone on and off and I will await her response. Like I said, if I have to do it, no biggy, just let me know.

Thanks!
Alex

**Comment by nlottig94** [comment]
I can do that @ebeshero and @amielnicki !  I have to finish tweaking my Capstone right no, but when I am finished with that, I will type that up.  It will go on the Methodology page, correct?  And we have one, right Alex?

**Comment by alexthattalks** [comment]
Yea, we have one on there already. You can just add it to the page.

**Comment by brookestewart** [comment]
@amielnicki Just letting you know I was able to push to the website!

**Comment by nlottig94** [comment]
@amielnicki @ebeshero @blawrence719 @brookestewart  The methodology is up and running!!!  Give it a look over for me????  http://dickinson16.newtfire.org/methodologies.html

**Comment by ebeshero** [comment]
@nlottig94 First line: you're missing an apostrophe on teams mission (should be team's mission)
And...image mapping isn't really a new concept--it has been around a long time--I was making image maps back in the early 2000s before I knew anything about XML!

**Comment by ebeshero** [comment]
@nlottig94 But I love how you're featuring the brainstorming--and those are wonderful links into the team's GitHub! :+1:

**Comment by brookestewart** [comment]
@ebeshero I fixed the typos, but when exactly is the due date? I just have to finish the details to go along with the biography and proofread everything else. Tonight is really the only time I can work on it- I have a full schedule tomorrow, then I leave for Canada. Is the deadline strictly midnight?

**Comment by ebeshero** [comment]
@brookestewart It's not strictly midnight, and the group has a discretionary extension until tomorrow night at midnight should you need it.

**Comment by ebeshero** [comment]
Methodologies vs, Methodology?
And anyone notice the extra instructions for adding content in p tags on the Dash page?

**Comment by brookestewart** [comment]
Okay, that helps!
Yes! I'm still working on the dash page. I will remove that now. And change the Methodology.

**Comment by nlottig94** [comment]
@amielnicki can you change the name of the page to methodology instead of methodologies?

**Comment by nlottig94** [comment]
@brookestewart I think we should keep the word methodology.  And methodologies should be changed

**Comment by nlottig94** [comment]
We'll see if Alex answers before we do anything with it

**Comment by alexthattalks** [comment]
HEY! I just changed the dash page!

**Comment by alexthattalks** [comment]
Please sync before you do anything and modify that. I fixed the page display.

**Comment by ebeshero** [comment]
Yep--just saw that and deleted my comment! :+1:

**Comment by nlottig94** [comment]
So the methodology is fixed?

**Comment by alexthattalks** [comment]
I will change the methodologies to methodology. Give me five minutes and make sure you resync everything.

**Comment by nlottig94** [comment]
Perfect!!  And I'm nowhere near a computer, so we're fine :)

**Comment by alexthattalks** [comment]
I fixed all of the methodologies and display errors on the dash page. I have pushed all of my changes to github. PLEASE sync, and check out the site before you make any changes to make sure I didn't already make them. @nlottig94 @ebeshero @blawrence719 @brookestewart

**Comment by brookestewart** [comment]
Merge conflict with dash.html? It's doing the same thing that happened last week.

**Comment by alexthattalks** [comment]
It's because you were editing it, and I fixed and pushed it before you finished. Nicole is texting you

**Comment by alexthattalks** [comment]
I just added our group picture to the about page.

**Comment by alexthattalks** [comment]
I just added instructions to each poem so people know how the buttons work.

**Comment by brookestewart** [comment]
Okay, just a quick question. When you go click on the Analysis tab at the top, it takes you to a blank analysis page. Is something supposed to go there, or is it more of a leftover placeholder? Is the dash analysis fine where it is under the graph?

**Comment by brookestewart** [comment]
Also, when you click on the About tab on the top, the side button still says "Methodologies"

**Comment by nlottig94** [comment]
I also see this.  I don't know how to get rid of it though because I don't want to mess with Alex's stuff.. @ebeshero what should we do?  Should we just leave it the way it is and ask Alex about it when he gets back?

**Comment by nlottig94** [comment]
@amielnicki if you see this can you tell us what to do?

**Comment by alexthattalks** [comment]
You can correct it without running the XSLT on the about page, just change it in the html file.

As for the analysis page, it was just a placeholder. But don't delete it, because then there will be broken links.

I am taking off from DC now.

**Comment by alexthattalks** [comment]
Where it says "methodologies" in the file, just change it to "methodology" same with methodologies.html, just make it methodology.html on the about page

**Comment by nlottig94** [comment]
Okay, I will do that!  I'll just type up something small to put in the analysis page!  Have a great time!

**Comment by nlottig94** [comment]
Hello all!!  I do believe our website is complete!!!!!  (And it looks pretty darn good, if I do say so myself!)  Thanks for everyone's hard work!!  It was a pleasure working with you all!!  @amielnicki @brookestewart @blawrence719  @ebeshero 

Check the full site out!!!  http://dickinson16.newtfire.org

**Comment by ebeshero** [comment]
@amielnicki @brookestewart @blawrence719 @nlottig94 Huzzah! Congratulations, Team Dickinson! I'll take it that your project work for the semester is now complete. We'll send a detailed response as we wrap up the course grading early next week.

**Comment by alexthattalks** [comment]
Thank goodness!!!! I'm on my boat now! Bahamas here I come!
