### ISSUE TITLE
Ideas for Spring 2016

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/EmilyDickinson16#32]
@brookestewart and @blawrence719 
We need to come up with some ideas of what we want to do with Dickinson this semester.
Dr. B suggested that we could maybe mark up the poems in Liminal and then make a really cool graphic.
Start your suggestions here!!

**Comment by brookestewart** [comment]
I don't have any specific research ideas yet, but I think it would be a good idea to try to regularize our tagging. I noticed some variations with the published versions are tagged with only the variation in the `rdg` element, whereas others include the whole line where only one or two changes were made, such as a punctuation mark. I could work on this if we can agree how we want to tag the changes. I propose tagging them with as little inside the `rdg` element as possible so the focus would be on the change alone, not the whole line that contains the change. Does this make sense? Any thoughts?

**Comment by nlottig94** [comment]
- [ ] Make a bibliography page?
- [x] Fix SVG graph? (Lines instead of dots?)
- [ ] Fix the minor element bugs.
- [x] Run XSLT over the XMLs with the line numbers.
- [ ] Apply the Schematron
- [ ] Try Liminal to make cool new visualizations
- [ ] Fix coding errors 
- [x] Fix color of `am` because of similarity with `lSD`

**Comment by brookestewart** [comment]
Our research is going to begin with using Liminal to research overlapping hierarchies within Dickinson's original manuscripts.

**Comment by nlottig94** [comment]
@ebeshero Okay...So @brookestewart and I have decided that we don't want to focus our project on only experimenting with Liminal.  We have decided that we want to do what we did with Dickinson's Fascicle 16 with one of her other Fascicles and then maybe (eventually) try to do this for all of her Fascicles!  We are still going to fix the things that needed fixed (applying the Schematron, fix the SVG, make new visualizations, etc.), but we really want to try doing what we did with Fascicle 16 with another Fascicle (Fascicle 6).  I think our goal is to eventually have a fully functioning group of searchable websites dedicated to all of Dickinson's Fascicles.
Also, because of this, I am going to create another GitHub for Dickinson's Fascicle 6, so we can have things separated.

**Comment by nlottig94** [comment]
@ebeshero @ghbondar @RJP43 @spadafour
@brookestewart and I have a few new options for the Dash SVG Graph. [Check them out](https://github.com/ebeshero/EmilyDickinson16/tree/master/SVG_Files)! Let us know what you think and which we should use. We will be trying something different with the legend soon (suggestion from @spadafour).

**Comment by nlottig94** [comment]
@ebeshero @brookestewart 
At the request of @RJP43, I changed the color of Atlantic Monthly on the new SVG graph (still in progress and will be up soon!), on [the site](http://dickinson16.newtfire.org/1602.html), and on the Image Map (which required me to redo the photoshopping and the image mapping). Overall, it was an easy fix. Let me know what you think of the color!

**Comment by nlottig94** [comment]
[SEE THIS ISSUE](https://github.com/nlottig94/EmilyDickinson6/issues/9)
