### ISSUE TITLE
What to do for this week....

### ISSUE THREAD

**Issue by nlottig94** [ebeshero/EmilyDickinson16#5]
So I'm still not quite sure what we need to have accomplished with this project by tomorrow.  Is there any way you could help me out on something to do @ebeshero ?  I really appreciate it!!

**Comment by brookestewart** [comment]
I'm also unsure of what to do...

**Comment by ebeshero** [comment]
Well, you could try experimenting with something in the html layout...or even just start movin in some files in the new project webspace.

**Comment by nlottig94** [comment]
Okay, thanks!!

**Comment by nlottig94** [comment]
Okay, so I created a new folder and put all of the Fascicle 16 images in it.  Then I moved these to our webspace!  I figured it would be nice to have all of those images in one place.  I plan to maybe organize the rest of the pictures in folders, so we know which images go together.
