### ISSUE TITLE
Missing Image?

### ISSUE THREAD

**Issue by brookestewart** [ebeshero/EmilyDickinson16#8]
I'm checking for transcription errors in the poems, but there only seems to be one image for Poem 8 that cuts off in the middle of the poem. Any idea where the other image could be? @ebeshero @nlottig94 @blawrence719 @amielnicki

**Comment by ebeshero** [comment]
@brookestewart Brooke: Thanks for checking these carefully! Is this the image you're looking for?
http://www.cs.virginia.edu/cgi-bin/cgiwrap?user=ajf2j&script=BrowseSpace&BS_file=fascicle16.bsp&BS_node=fs1608&BS_edge=NextPage

This is one of the pages on Michele Ierardi's old site. Try browsing that site for images if I'm missing them on my pages.

**Comment by brookestewart** [comment]
Yes! Thank you @ebeshero!
